version: '2'

networks:
  nginx-proxy:
    external:
      name: web

services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-proxy  
    volumes:
      - certs:/etc/nginx/certs:ro
      - nginx_config:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - log:/var/log/nginx/
      - /var/run/docker.sock:/tmp/docker.sock:ro  
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ""

  let:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: let
    volumes_from:
      - proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  log:
    driver: local
  html:
    driver: local
  vhost:
    driver: local
  certs:
    driver: local
  nginx_config:
    driver: local
  dhparam:
    driver: local